"""On-the-fly UiPath Cross-Platform Python .nupkg builder (CONTEXT.md D-15..D-18).

Pure function — no disk I/O for the output. Returns the .nupkg bytes
directly so callers (Plan 11-05 ui_deploy_process) can stream them straight
to OrchestratorClient.upload_package.

Templates copied verbatim from the authoritative UiPath Python SDK
cli_pack.py (RESEARCH.md Finding 4). Do NOT improvise — every field is
schema-locked at https://cloud.uipath.com/draft/2024-12/entry-point.

NOTE: D-16 in CONTEXT.md mentions ``content/project.json``. The CORRECT
file (per Finding 4 verification against the live UiPath SDK) is
``content/operate.json``. We follow Finding 4, not D-16's wording.
"""
from __future__ import annotations

import io
import json
import uuid
import zipfile
from pathlib import Path
from string import Template

_CONTENT_TYPES = """<?xml version="1.0" encoding="utf-8"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml" />
  <Default Extension="psmdcp" ContentType="application/vnd.openxmlformats-package.core-properties+xml" />
  <Default Extension="json" ContentType="application/octet" />
  <Default Extension="py" ContentType="application/octet" />
  <Default Extension="txt" ContentType="application/octet" />
  <Default Extension="nuspec" ContentType="application/octet" />
</Types>
"""

_RELS_TPL = Template("""<?xml version="1.0" encoding="utf-8"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Type="http://schemas.microsoft.com/packaging/2010/07/manifest" Target="$nuspecPath" Id="$nuspecId" />
  <Relationship Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="$psmdcpPath" Id="$psmdcpId" />
</Relationships>
""")

# NOTE: leading \ufeff produces UTF-8 BOM required by NuGet (Pitfall 5).
_NUSPEC_TPL = Template("""\ufeff<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2011/10/nuspec.xsd">
  <metadata>
    <id>$packageName</id>
    <version>$packageVersion</version>
    <authors>$authors</authors>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>$description</description>
  </metadata>
</package>
""")

_PSMDCP_TPL = Template("""<?xml version="1.0" encoding="utf-8"?>
<coreProperties xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.openxmlformats.org/package/2006/metadata/core-properties">
  <dc:creator>$creator</dc:creator>
  <dc:description>$description</dc:description>
  <dc:identifier>$projectName</dc:identifier>
  <version>$packageVersion</version>
  <keywords></keywords>
  <lastModifiedBy>NuGet.Packaging, Version=6.12.1.1, Culture=neutral, PublicKeyToken=$publicKeyToken;.NET 5.0</lastModifiedBy>
</coreProperties>
""")


def build_nupkg(script_path: Path, workflow_name: str, version: str) -> bytes:
    """Build a UiPath Cross-Platform Python .nupkg and return its bytes.

    Pure function: reads ``script_path`` for the Main.py content; does NOT
    write any files to disk. Returns the complete .nupkg as bytes ready
    for ``OrchestratorClient.upload_package``.

    Args:
        script_path: Path to the generated Python script. The file is read
            in UTF-8 and embedded as ``content/Main.py`` inside the package.
        workflow_name: Used as the NuGet package id and the nuspec filename.
        version: Used as the NuGet package version (e.g. ``"1.0.0"``).

    Returns:
        Bytes of a valid UiPath Cross-Platform Python .nupkg.
    """
    script_text = script_path.read_text(encoding="utf-8")
    project_id = str(uuid.uuid4())
    entrypoint_id = str(uuid.uuid4())

    psmdcp_random = uuid.uuid4().hex[:16] + ".psmdcp"
    psmdcp_path = f"/package/services/metadata/core-properties/{psmdcp_random}"
    nuspec_path = f"/{workflow_name}.nuspec"

    rels_content = _RELS_TPL.substitute(
        nuspecPath=nuspec_path,
        nuspecId="R" + uuid.uuid4().hex[:16],
        psmdcpPath=psmdcp_path,
        psmdcpId="R" + uuid.uuid4().hex[:16],
    )
    nuspec_content = _NUSPEC_TPL.substitute(
        packageName=workflow_name,
        packageVersion=version,
        authors="yigthinker",
        description=f"Generated by yigthinker-mcp-uipath: {workflow_name}",
    )
    psmdcp_content = _PSMDCP_TPL.substitute(
        creator="yigthinker",
        description=f"Generated by yigthinker-mcp-uipath: {workflow_name}",
        projectName=workflow_name,
        packageVersion=version,
        publicKeyToken=uuid.uuid4().hex[:32],
    )

    operate_json = {
        "$schema": "https://cloud.uipath.com/draft/2024-12/entry-point",
        "projectId": project_id,
        "main": "Main.py",
        "contentType": "Process",
        "targetFramework": "Portable",
        "targetRuntime": "python",
        "runtimeOptions": {
            "requiresUserInteraction": False,
            "isAttended": False,
            "isConversational": False,
        },
    }
    entry_points_json = {
        "$schema": "https://cloud.uipath.com/draft/2024-12/entry-point",
        "$id": "entry-points.json",
        "entryPoints": [
            {
                "filePath": "Main.py",
                "uniqueId": entrypoint_id,
                "type": "process",
                "input": {"type": "object", "properties": {}, "required": []},
                "output": {"type": "object", "properties": {}, "required": []},
            }
        ],
    }

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr(
            f"package/services/metadata/core-properties/{psmdcp_random}",
            psmdcp_content,
        )
        zf.writestr("[Content_Types].xml", _CONTENT_TYPES)
        zf.writestr("content/operate.json", json.dumps(operate_json, indent=2))
        zf.writestr(
            "content/entry-points.json", json.dumps(entry_points_json, indent=2)
        )
        zf.writestr("content/Main.py", script_text)
        zf.writestr(f"{workflow_name}.nuspec", nuspec_content)
        zf.writestr("_rels/.rels", rels_content)
    return buf.getvalue()
